# Manipulación de Arrays

**Métodos de creación de Arrays de NumPy**

NumPy proporciona diversas maneras de crear arrays, facilitando la realización de cálculos numéricos y análisis de datos de manera eficiente en Python.

### **1. Creación de Arrays a partir de Listas**

Podemos crear un array a partir de una lista o una lista de listas:

In [1]:
import numpy as np

# Array unidimensional
array_1d = np.array([1, 2, 3, 4])
print(array_1d.ndim)
print(array_1d.shape)
print(array_1d.dtype)

1
(4,)
int64


In [2]:
# Array bidimensional
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d.ndim)
print(array_2d.shape)
print(array_2d.dtype)

2
(2, 3)
int64


### **2. Creación de Arrays con Funciones Predefinidas**

NumPy proporciona funciones predefinidas para crear arrays de manera más rápida y conveniente:

* `np.zeros()`: Crea un array lleno de ceros.

In [3]:
zeros_array = np.zeros((3, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


* `np.ones()`: Crea un array lleno de unos.

In [4]:
ones_array = np.ones((2, 4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


* `np.arange()`: Crea un array con una secuencia de números.

In [5]:
range_array = np.arange(0, 10, 2)
print(range_array)

[0 2 4 6 8]


* `np.linspace()`: Crea un array con números igualmente espaciados.

In [6]:
linspace_array = np.linspace(0, 1, 5)
print(linspace_array)

[0.   0.25 0.5  0.75 1.  ]


### **3. Especificando Tipos de Datos (Datatypes)**

Al crear un array, podemos especificar el tipo de datos que contendrá utilizando el parámetro `dtype`. Esta especificación es crucial para la eficiencia y precisión en cálculos numéricos. Aquí se detallan algunos de los tipos de datos más comunes:

* `int32`: Entero de 32 bits.
* `float32`: Número de punto flotante de 32 bits.
* `float64`: Número de punto flotante de 64 bits (por defecto para números flotantes en NumPy).
* `bool`: Valores booleanos (True o False).
* `complex64`: Número complejo de 64 bits.
* `complex128`: Número complejo de 128 bits.
* `str`: Cadenas de texto.

Podemos especificar estos tipos de datos al crear el array utilizando el parámetro `dtype`:

In [7]:
# Array de enteros
int_array = np.array([1, 2, 3], dtype='int32')
print(int_array)

# Array de flotantes
float_array = np.array([1.0, 2.0, 3.0], dtype='float32')
print(float_array)

# Array de booleanos
bool_array = np.array([True, False, True], dtype='bool')
print(bool_array)

# Array de números complejos
complex_array = np.array([1+2j, 3+4j], dtype='complex64')
print(complex_array)

# Array de cadenas de texto
str_array = np.array(['a', 'b', 'c'], dtype='str')
print(str_array)

[1 2 3]
[1. 2. 3.]
[ True False  True]
[1.+2.j 3.+4.j]
['a' 'b' 'c']


Algunos de estos tipos también pueden ser especificados con abreviaturas en el parámetro `dtype`.

Por ejemplo, `'d'` es equivalente a `float64`, que es el tipo de datos de punto flotante de 64 bits en NumPy:

In [8]:
array_float64 = np.array([1, 2, 3], dtype='d')
print(array_float64)

[1. 2. 3.]


### **4. NaN (Not a Number)**

NaN es un valor especial utilizado para representar datos que no son números, especialmente en el contexto de operaciones matemáticas que no tienen un resultado definido. Por ejemplo, la división de cero por cero (0/0) o la raíz cuadrada de un número negativo.

In [9]:
nan_array = np.array([1, 2, np.nan, 4])
print(nan_array)

[ 1.  2. nan  4.]


El valor NaN es muy útil para manejar datos faltantes o resultados indefinidos en cálculos numéricos.