# Álgebra Lineal Aplicada

El álgebra lineal es una rama fundamental de las matemáticas que se centra en el estudio de los vectores, las matrices y las transformaciones lineales. NumPy proporciona herramientas para resolver sistemas de ecuaciones lineales, realizar transformaciones geométricas y modelar problemas en diversas áreas de la ciencia y la ingeniería. Su aplicación es tan amplia que se encuentra en el corazón de múltiples disciplinas científicas y tecnológicas, facilitando desde la simulación de fenómenos físicos hasta la optimización de sistemas complejos.

Los vectores y las matrices, los bloques de construcción del álgebra lineal, nos permiten representar y manipular datos de manera eficiente, un vector puede representar una lista de valores que podrían ser coordenadas espaciales, mientras que una matriz puede representar una transformación que afecta a estos vectores. Las operaciones básicas del álgebra lineal, como la suma, la multiplicación y la transposición de matrices, forman la base de muchas técnicas avanzadas en la física, la ingeniería, la economía y la informática.

### **Conceptos básicos de álgebra lineal**
1. **Vectores:** Son objetos que tienen magnitud y dirección. Se pueden representar como una lista de números, que son las coordenadas del vector.
2. **Matrices:** Son arreglos bidimensionales de números que representan transformaciones lineales. Una matriz puede transformar un vector en otro vector.
3. **Transformaciones Lineales:** Son funciones que toman vectores como entrada y producen otros vectores como salida, respetando las operaciones de suma y multiplicación por un escalar.
4. **Espacios Vectoriales:** Conjuntos de vectores que pueden sumarse entre sí y multiplicarse por escalares, siguiendo ciertas reglas.

### **Ejemplos aplicativos**
1. **Gráficos por Computadora:** Las transformaciones lineales se utilizan para rotar, escalar y traducir objetos en la pantalla.
2. **Procesamiento de Imágenes:** Las matrices de convolución (kernels) se usan para aplicar filtros a las imágenes, mejorando su calidad o destacando características específicas.
3. **Aprendizaje Automático:** Los algoritmos de regresión lineal, redes neuronales y otros modelos dependen en gran medida de las operaciones matriciales.

### **Operaciones principales en álgebra lineal**
Vamos a ver algunas de las operaciones más comunes en álgebra lineal utilizando matrices.

#### **Suma de matrices**
La suma de matrices se realiza elemento por elemento. Por ejemplo, si tenemos dos matrices A y B:

$$
A = 
    \begin{pmatrix}
        1 & 2 \\
        3 & 4
    \end{pmatrix}
$$

$$
B = 
    \begin{pmatrix}
        5 & 6 \\
        7 & 8
    \end{pmatrix}
$$

La suma de $A$ y $B$ es:
$$
A + B = 
    \begin{pmatrix}
        1 + 5 & 2 + 6 \\
        3 + 7 & 4 + 8
    \end{pmatrix}
=
    \begin{pmatrix}
        6 & 8 \\
        10 & 12
    \end{pmatrix}
$$

Código en NumPy para la suma de matrices:

In [1]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

suma = A + B
print("Suma de matrices:\n", suma)

Suma de matrices:
 [[ 6  8]
 [10 12]]


#### **Multiplicación de matrices**
La multiplicación de matrices combina filas de una matriz con columnas de otra. Por ejemplo, si tenemos las mismas matrices A y B:

$$
A = 
    \begin{pmatrix}
        1 & 2 \\
        3 & 4
    \end{pmatrix}
$$

$$
B = 
    \begin{pmatrix}
        5 & 6 \\
        7 & 8
    \end{pmatrix}
$$

El producto de $A$ y $B$ es:
$$
A \cdot B = 
    \begin{pmatrix}
        (1 \cdot 5 + 2 \cdot 7) & (1 \cdot 6 + 2 \cdot 8) \\
        (3 \cdot 5 + 4 \cdot 7) & (3 \cdot 6 + 4 \cdot 8)
    \end{pmatrix}
=
    \begin{pmatrix}
        19 & 22 \\
        43 & 50
    \end{pmatrix}
$$

Código en NumPy para la multiplicación de matrices:

In [2]:
producto = np.dot(A, B)
print("Producto de matrices:\n", producto)

Producto de matrices:
 [[19 22]
 [43 50]]


#### **Transposición de Matrices**
La transposición de una matriz intercambia sus filas y columnas. Por ejemplo, la transposición de la matriz A es:

$$
A = 
    \begin{pmatrix}
        1 & 2 \\
        3 & 4
    \end{pmatrix}
$$

$$
A^T = 
    \begin{pmatrix}
        1 & 3 \\
        2 & 4
    \end{pmatrix}
$$

Código en NumPy para la transposición de matrices:

In [3]:
transpuesta = A.transpose()
print('Transpuesta de matrices:\n',transpuesta)

Transpuesta de matrices:
 [[1 3]
 [2 4]]


#### Determinante de una matriz
El determinante es un valor único que puede calcularse a partir de una matriz cuadrada. Por ejemplo, el determinante de la matriz A es:

$$
A = 
    \begin{pmatrix}
        1 & 2 \\
        3 & 4
    \end{pmatrix}
$$

El determinante de $A$, denotado como $det(A)$, se calcula como:
$$
det(A) = (1 \cdot 4) - (2 \cdot 3) = 4 - 6 = -2
$$

In [4]:
determinante = np.linalg.det(A)
print("Determinante de A:", determinante)

Determinante de A: -2.0000000000000004


#### **Más operaciones de álgebra lineal con NumPy**
NumPy ofrece una variedad de funciones que facilitan el trabajo con álgebra lineal. Aquí hay algunas más:

#### **Inversa de una matriz**
La matriz inversa de A:

La matriz inversa de $A$ es una matriz $A^{-1}$ tal que $A \cdot A^{-1} = I$ donde $I$ es la matriz identidad.

In [5]:
inversa = np.linalg.inv(A)
print("Inversa de A:\n", inversa)

Inversa de A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


#### **Valores y vectores propios**
Los valores propios y los vectores propios son fundamentales en muchas aplicaciones, como en la compresión de datos y el análisis de sistemas dinámicos.

In [ ]:
valores_propios, vectores_propios = np.linalg.eig(A)
print("Valores propios de A:\n", valores_propios)
print("Vectores propios de A:\n", vectores_propios)

Valores propios de A:
 [-0.37228132  5.37228132]
Vectores propios de A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


#### **Resolución de sistemas de ecuaciones lineales**
Para resolver un sistema de ecuaciones lineales $Ax=B$:

In [7]:
B = np.array([1, 2])
X = np.linalg.solve(A, B)
print("Solución del sistema AX = B:\n", X)

Solución del sistema AX = B:
 [0.  0.5]


NumPy es una herramienta poderosa para manejar cálculos numéricos y operaciones de álgebra lineal en Python. Su eficiencia y facilidad de uso la convierten en una biblioteca indispensable para científicos de datos, ingenieros y desarrolladores. Desde la creación de arrays hasta la manipulación de imágenes, NumPy abre un mundo de posibilidades en diversas aplicaciones del mundo real.