# Indexación y Slicing

Forma de acceder a los elementos de un array por medio de su índice.

Los indices empiezan a partir del 0 que representa el primer elemento del array.

In [1]:
import numpy as np

array = np.array([10, 20, 30, 40, 50])
print(array[1]) # Acceso al segundo elemento
print(array[-1]) # Acceso al último elemento

20
50


In [2]:
print(array[1:4]) # Acceso a un rango de elementos

[20 30 40]


In [3]:
print(array[1:7]) # Acceso a un rango de elementos (hasta el final)

[20 30 40 50]


In [4]:
print(array[-1:-7]) # Como excede el rango, no devuelve nada

[]


In [5]:
array

array([10, 20, 30, 40, 50])

In [6]:
bool_index = array > 25
bool_index

array([False, False,  True,  True,  True])

In [7]:
index = [2,0,4]
print(array[index]) # Acceso a elementos específicos por índice

[30 10 50]


In [8]:
array = np.random.randint(1, 10, (3, 3)) # Generación de un array 3x3 con números aleatorios entre 1 y 10
print(array)
print(array[0, 1]) # Acceso al elemento en la primera fila y segunda columna

[[2 2 2]
 [2 1 3]
 [5 3 1]]
2


In [9]:
print(array[:2, :2]) # Acceso a un subarray de las primeras dos filas y columnas

[[2 2]
 [2 1]]


### Ejercicios para practicar Indexación y Slicing:
1. **Acceder a elementos específicos:**
   * Crea un arreglo de 10 números y accede al cuarto y penúltimo elemento usando índices positivos y negativos.
2. **Slicing de arreglos:**
   * Dado un arreglo de números del 1 al 20, extrae los elementos entre las posiciones 3 y 7, y luego los elementos de las últimas 5 posiciones.
3. **Indexing con booleanos:**
   * Crea un arreglo de números aleatorios entre 0 y 100. Usa una expresión booleana para acceder solo a los números mayores a 50.
4. **Indexación con múltiples índices:**
   * Dado un arreglo de 8 elementos, crea una lista de índices para acceder a los elementos en las posiciones 1, 4, y 6.
5. **Matrices bidimensionales:**
   * Genera una matriz 4x4 de números aleatorios entre 10 y 50, y accede a la submatriz de 2x2 ubicada en la esquina inferior derecha.

In [10]:
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(array[[3, -2]])

[40 90]


In [11]:
array = np.arange(1, 21)
print(array[3:7])
print(array[-5:])

[4 5 6 7]
[16 17 18 19 20]


In [12]:
array = np.arange(1, 101)
bool_index = array > 50
print(array[bool_index]) # Acceso a elementos mayores a 50

[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


In [13]:
array = np.arange(0, 8)
print(array[[1,4,6]])

[1 4 6]


In [14]:
array_2d  = np.random.randint(10, 50, (4, 4)) # Generación de un array 2D 3x3 con números aleatorios entre 1 y 10
print(array_2d)
print(array_2d[-2:,-2:]) 

[[49 13 41 11]
 [35 48 43 17]
 [10 21 28 39]
 [12 18 22 29]]
[[28 39]
 [22 29]]
