# Operaciones con Arrays en NumPy: Broadcasting, Concatenación y Más

## ¿Qué es broadcasting en NumPy?

**Broadcasting** es una funcionalidad poderosa en NumPy que permite realizar operaciones aritméticas en arrays de diferentes tamaños y formas de manera eficiente. En lugar de iterar sobre cada elemento de los arrays para realizar las operaciones, NumPy extiende automáticamente los arrays más pequeños para que coincidan con las dimensiones de los más grandes, sin duplicar datos. Esto no solo optimiza el uso de la memoria, sino que también acelera significativamente las operaciones.

El broadcasting permite que las operaciones entre arrays de diferentes dimensiones se realicen como si todos los arrays tuvieran la misma forma. NumPy extiende los arrays más pequeños a la forma del más grande de manera implícita, facilitando las operaciones sin necesidad de copiar los datos.

### **Aplicaciones de Broadcasting**

* **Aplicación de Descuentos:** Supongamos que tenemos un array que representa los precios de varios productos y otro array con un descuento porcentual que se aplica a todos los productos. Con broadcasting, podemos aplicar el descuento sin necesidad de un bucle explícito.

In [1]:
import numpy as np

prices = np.array([100, 200, 300])
discount = np.array([0.9])
discounted_prices = prices * discount
print(discounted_prices)

[ 90. 180. 270.]


* **Operaciones con Arrays Multidimensionales:** Podemos realizar operaciones elementales entre arrays de diferentes dimensiones.

In [2]:
a = np.array(
                [
                    [0.0, 0.0, 0.0],
                    [10.0, 10.0, 10.0],
                    [20.0, 20.0, 20.0],
                    [30.0, 30.0, 30.0]
                ]
            )
b = np.array([1.0, 2.0, 3.0])
result = a + b
print(result)

[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


### **Importancia del Broadcasting**

Broadcasting es crucial porque permite escribir código más conciso y legible, evitando bucles explícitos y aprovechando las optimizaciones internas de NumPy para realizar operaciones de manera rápida y eficiente. Esto es especialmente útil en análisis de datos y aprendizaje automático, donde se manejan grandes volúmenes de datos y se requieren cálculos rápidos.

#### **Reglas de Broadcasting**

Para que el broadcasting funcione, las dimensiones de los arrays deben cumplir ciertas reglas:

1. **Comparación desde la Última Dimensión:** Las dimensiones se comparan desde la última hacia la primera.
2. **Dimensiones Compatibles:** Dos dimensiones son compatibles si son iguales o si una de ellas es 1.

Ejemplos:

* **Escalar y Array 1D:**

In [3]:
a = np.array([1, 2, 3])
b = 2
result = a * b
print(result)

[2 4 6]


* **Array 1D y Array 2D:**

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1, 0, 1])
result = a * b
print(result)

[[1 0 3]
 [4 0 6]
 [7 0 9]]


* **Array 2D y Array 3D:**

In [5]:
a = np.array([[[1], [2], [3]], [[4], [5], [6]]])
b = np.array([1, 2, 3])
result = a * b
print(result)

[[[ 1  2  3]
  [ 2  4  6]
  [ 3  6  9]]

 [[ 4  8 12]
  [ 5 10 15]
  [ 6 12 18]]]


Broadcasting en NumPy es una técnica esencial para realizar operaciones aritméticas de manera eficiente en arrays de diferentes tamaños y formas. Entender y aplicar las reglas de broadcasting permite escribir código más limpio y optimizado, crucial para tareas de análisis de datos y aprendizaje automático.

In [6]:
array = np.array([1,2,3,4,5])
print(np.all(array > 9)) # Verifica si todos los elementos son mayores que 9

False


In [7]:
print(np.any(array > 9)) # Verifica si al menos un elemento es mayor que 9

False


### **Concatenación**

Concatenación nos permite unir uno o mas arrays para tener uno solo

In [8]:
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

In [9]:
concatenada_aa = np.concatenate((array_a, array_a))
concatenada_ab = np.concatenate((array_a, array_b))
print(concatenada_aa)
print(concatenada_ab)

[1 2 3 1 2 3]
[1 2 3 4 5 6]


### **Stacking**

Nos permite apilar arrays o darles otra dimensionalidad especificando que queremos.

In [10]:
stacked_v = np.vstack((array_a, array_b))
print(stacked_v)

[[1 2 3]
 [4 5 6]]


In [11]:
stacked_h = np.hstack((array_a, array_b))
print(stacked_h)

[1 2 3 4 5 6]


### **Split**

Dividir un array grande en arrays más pequeños.

In [12]:
array_c = np.arange(1, 10)
split_arrays = np.array_split(array_c, 3)
print(array_c)
print(split_arrays)

[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


##