# Análisis de Ventas Mensuales con NumPy: Transformaciones y Insights

## Ejercicio: Análisis de Ventas Mensuales con NumPy

El objetivo de este ejercicio es trabajar con arrays de NumPy para analizar y manipular datos de ventas de tres productos a lo largo de un año. A través de diversas operaciones, explorarás cómo usar NumPy para obtener estadísticas, realizar manipulaciones avanzadas y aplicar técnicas de indexación para extraer información clave.

In [1]:
import numpy as np

## Instrucciones:

### Paso 1: Crear Arrays con Datos de Ventas

* Usa la librería numpy para crear los siguientes arrays:

    - meses: un array con los nombres de los meses del año.

    - ventas_A, ventas_B, ventas_C: arrays que representan las ventas mensuales de tres productos diferentes.

In [2]:
months = np.array([
    'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 
    'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'
])

product_A = np.array([150, 200, 250, 300, 220, 210, 180, 190, 230, 240, 280, 300])
product_B = np.array([180, 210, 230, 250, 270, 260, 240, 250, 270, 290, 310, 330])
product_C = np.array([200, 220, 240, 260, 280, 300, 320, 340, 360, 380, 400, 420])

## Paso 2: Estadísticas Básicas

* Calcula la media y la suma de ventas para los productos A, B y C usando las funciones de NumPy.
* Imprime estos valores en el formato siguiente:
* Media de ventas Producto A: <valor>
* Suma de ventas Producto A: <valor>
* Repite para los productos B y C.

In [3]:
media_A = np.mean(product_A)
suma_A = np.sum(product_A)

media_B = np.mean(product_B)
suma_B = np.sum(product_B)

media_C = np.mean(product_C)
suma_C = np.sum(product_C)

print(f"Media de ventas Producto A: {media_A}")
print(f"Suma de ventas Producto A: {suma_A}")

print(f"Media de ventas Producto B: {media_B}")
print(f"Suma de ventas Producto B: {suma_B}")

print(f"Media de ventas Producto C: {media_C}")
print(f"Suma de ventas Producto C: {suma_C}")


Media de ventas Producto A: 229.16666666666666
Suma de ventas Producto A: 2750
Media de ventas Producto B: 257.5
Suma de ventas Producto B: 3090
Media de ventas Producto C: 310.0
Suma de ventas Producto C: 3720


### Paso 3: Manipulación y Análisis de Datos

* Total de ventas por mes: Suma las ventas de los tres productos para cada mes.
* Promedio de ventas por producto: Calcula el promedio de ventas por producto.
* Mes con mayor y menor ventas: Identifica qué mes tuvo el total de ventas más alto y cuál el más bajo usando las funciones np.argmax y np.argmin.

In [4]:
ventas_por_mes = product_A + product_B + product_C
print("Ventas por mes:")
for i, mes in enumerate(months):
    print(f"{mes}: {ventas_por_mes[i]}")

promedio_ventas_producto_A = np.mean(product_A)
promedio_ventas_producto_B = np.mean(product_B)
promedio_ventas_producto_C = np.mean(product_C)
print(f"Promedio de ventas del producto A: {promedio_ventas_producto_A}")
print(f"Promedio de ventas del producto B: {promedio_ventas_producto_B}")
print(f"Promedio de ventas del producto C: {promedio_ventas_producto_C}")

mes_con_mayor_ventas = np.argmax(ventas_por_mes)
mes_con_menor_ventas = np.argmin(ventas_por_mes)
print(f"Mes con mayor ventas: {months[mes_con_mayor_ventas]}")
print(f"Mes con menor ventas: {months[mes_con_menor_ventas]}")

Ventas por mes:
Enero: 530
Febrero: 630
Marzo: 720
Abril: 810
Mayo: 770
Junio: 770
Julio: 740
Agosto: 780
Septiembre: 860
Octubre: 910
Noviembre: 990
Diciembre: 1050
Promedio de ventas del producto A: 229.16666666666666
Promedio de ventas del producto B: 257.5
Promedio de ventas del producto C: 310.0
Mes con mayor ventas: Diciembre
Mes con menor ventas: Enero


### Paso 4: Operaciones Avanzadas con NumPy

Reshape y Transposición:

* Crea una matriz 2D con las ventas de los tres productos y transforma su forma (reshape) a un array tridimensional con dimensiones (3, 4, 3).
* Transpone la matriz de ventas para que las filas se conviertan en columnas.
* Invertir arrays: Invierte las ventas de cada producto en orden de meses.
* Aplanar la matriz: Convierte la matriz de ventas a un array unidimensional.

In [5]:
matriz_ventas = np.array([product_A, product_B, product_C])
print("Matriz de ventas:")
print(matriz_ventas)

reshaped_matriz = matriz_ventas.reshape(3,4,3)
reshaped_matriz_T = reshaped_matriz.T
print("Matriz de ventas reshaped:")
print(reshaped_matriz_T)

ventas_invertidas_A = product_A[::-1]
ventas_invertidas_B = product_B[::-1]
ventas_invertidas_C = product_C[::-1]
print("Ventas invertidas Producto A:", ventas_invertidas_A)
print("Ventas invertidas Producto B:", ventas_invertidas_B)
print("Ventas invertidas Producto C:", ventas_invertidas_C)

ventas_aplanadas = matriz_ventas.flatten()
print("Ventas aplanadas:", ventas_aplanadas)

Matriz de ventas:
[[150 200 250 300 220 210 180 190 230 240 280 300]
 [180 210 230 250 270 260 240 250 270 290 310 330]
 [200 220 240 260 280 300 320 340 360 380 400 420]]
Matriz de ventas reshaped:
[[[150 180 200]
  [300 250 260]
  [180 240 320]
  [240 290 380]]

 [[200 210 220]
  [220 270 280]
  [190 250 340]
  [280 310 400]]

 [[250 230 240]
  [210 260 300]
  [230 270 360]
  [300 330 420]]]
Ventas invertidas Producto A: [300 280 240 230 190 180 210 220 300 250 200 150]
Ventas invertidas Producto B: [330 310 290 270 250 240 260 270 250 230 210 180]
Ventas invertidas Producto C: [420 400 380 360 340 320 300 280 260 240 220 200]
Ventas aplanadas: [150 200 250 300 220 210 180 190 230 240 280 300 180 210 230 250 270 260
 240 250 270 290 310 330 200 220 240 260 280 300 320 340 360 380 400 420]


### Paso 5: Análisis de Elementos Únicos

Utiliza np.unique para encontrar los elementos únicos en los datos de ventas y cuenta cuántas veces aparece cada uno.

In [6]:
ventas_unicas, counts = np.unique(ventas_aplanadas, return_counts=True)
print("Elementos únicos en ventas:", ventas_unicas)
print("Conteo de elementos únicos:", counts)

Elementos únicos en ventas: [150 180 190 200 210 220 230 240 250 260 270 280 290 300 310 320 330 340
 360 380 400 420]
Conteo de elementos únicos: [1 2 1 2 2 2 2 3 3 2 2 2 1 3 1 1 1 1 1 1 1 1]


### Paso 6: Indexación y Slicing

* Ventas del primer trimestre: Extrae las ventas de los tres primeros meses del año.
* Indexación booleana: Selecciona los meses donde el total de ventas de los tres productos supere los 800.
* Selección avanzada: Usa una lista de índices para seleccionar las ventas de los meses pares (o selecciona los meses a tu elección) y muestra esas ventas en una nueva matriz.

In [7]:
venta_primer_trimestre = ventas_por_mes[:3]
print("Ventas del primer trimestre:", venta_primer_trimestre)

venta_mayor_800 = ventas_por_mes > 800
meses_mayor_800 = months[venta_mayor_800]
print(f"Meses con total de ventas mayor a 800: {meses_mayor_800}")

indices_pares = np.arange(0,12,2)
ventas_meses_pares = ventas_por_mes[indices_pares]
print(f"Ventas en meses pares: {ventas_meses_pares}")

Ventas del primer trimestre: [530 630 720]
Meses con total de ventas mayor a 800: ['Abril' 'Septiembre' 'Octubre' 'Noviembre' 'Diciembre']
Ventas en meses pares: [530 720 770 740 860 990]
