# Conexión de NumPy con Pandas y Matplotlib para Análisis de Datos

¡Felicidades por llegar al final del primer módulo! Has aprendido a dominar NumPy, una herramienta fundamental para el análisis de datos. Este es un gran paso en tu camino para convertirte en un experto en ciencia de datos. Pero esto es solo el comienzo. En los próximos módulos, nos adentraremos en dos poderosas herramientas: **Pandas** y **Matplotlib**, que se integran de manera perfecta con NumPy para llevar tu análisis de datos al siguiente nivel.

## Conexión entre NumPy, Pandas y Matplotlib

**1. NumPy como Fundamento**

* NumPy es la base sobre la que se construyen muchas otras librerías de análisis de datos en Python, incluidas Pandas y Matplotlib.
* Con NumPy, has aprendido a manejar arrays multidimensionales y realizar cálculos matemáticos y matriciales eficientes. Estos arrays son fundamentales porque Pandas y Matplotlib los utilizan bajo el capó para realizar muchas de sus operaciones.

**2. Pandas para la Manipulación de Datos**

* Mientras que NumPy se especializa en operaciones numéricas y matriciales, Pandas es la herramienta que utilizarás para la manipulación de datos estructurados, como tablas y series temporales.
* Pandas toma los arrays de NumPy y les da estructura en forma de **DataFrames** y **Series**, lo que facilita la limpieza, transformación y análisis de datos complejos.
* **Ejemplo de Conexión:** Puedes usar NumPy para realizar cálculos en un conjunto de datos, luego importar esos resultados a un DataFrame de Pandas para un análisis más detallado.

**3. Matplotlib para la Visualización de Datos**

* Matplotlib es la librería de referencia para la visualización de datos en Python. Te permitirá transformar tus datos en gráficos e imágenes que comunican claramente tus hallazgos.
* Tanto NumPy como Pandas se integran perfectamente con Matplotlib, permitiéndote crear gráficos desde arrays de NumPy o directamente desde DataFrames de Pandas.
* **Ejemplo de Conexión:** Después de procesar y analizar datos con NumPy y Pandas, puedes usar Matplotlib para crear gráficos que visualicen las tendencias, patrones y anomalías en los datos.

**4. El Flujo de Trabajo Completo**

* **Cargar y Manipular Datos:** Utilizas Pandas para cargar y estructurar tus datos desde diversas fuentes (como CSVs, Excel, bases de datos).
* **Análisis Numérico y Cálculos:** Usas NumPy para realizar cálculos intensivos, como operaciones matriciales y simulaciones.
* **Visualización de Resultados:** Finalmente, Matplotlib te ayuda a visualizar los resultados de tus análisis, creando gráficos que pueden comunicarse efectivamente con tu audiencia.

## Ejercicios Prácticos con NumPy

Vamos a consolidar lo que has aprendido con ejercicios exclusivos de NumPy, diseñados para reforzar tus habilidades y prepararte para las conexiones futuras con Pandas y Matplotlib.

**1. Operaciones Básicas con Arrays**

* **Instrucción:** Crea dos arrays de 1D con valores enteros y realiza las operaciones de suma, resta, multiplicación, y división entre ellos.
* **Código:**

In [1]:
import numpy as np

array1 = np.array([10, 20, 30, 40])
array2 = np.array([1, 2, 3, 4])

suma = array1 + array2
resta = array1 - array2
multiplicacion = array1 * array2
division = array1 / array2

print("Suma:", suma)
print("Resta:", resta)
print("Multiplicación:", multiplicacion)
print("División:", division)

Suma: [11 22 33 44]
Resta: [ 9 18 27 36]
Multiplicación: [ 10  40  90 160]
División: [10. 10. 10. 10.]


**2. Cálculos Estadísticos en Arrays**

* **Instrucción:** Dado un array de datos, calcula la media, mediana, varianza, y desviación estándar.
* **Código:**

In [2]:
import numpy as np

datos = np.array([23, 76, 35, 67, 89, 45, 68, 79, 35])

media = np.mean(datos)
mediana = np.median(datos)
varianza = np.var(datos)
desviacion = np.std(datos)

print("Media:", media)
print("Mediana:", mediana)
print("Varianza:", varianza)
print("Desviación estándar:", desviacion)

Media: 57.44444444444444
Mediana: 67.0
Varianza: 484.02469135802465
Desviación estándar: 22.000561160071


**3. Operaciones Matriciales**

* **Instrucción:** Crea dos matrices de 2x2 y realiza las operaciones de suma, resta, multiplicación (producto matricial) y cálculo de la inversa de una de ellas.
* **Código:**

In [3]:
import numpy as np

matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])

suma_matrices = matriz1 + matriz2
resta_matrices = matriz1 - matriz2
producto_matrices = np.dot(matriz1, matriz2)
inversa_matriz1 = np.linalg.inv(matriz1)

print("Suma de matrices:\n", suma_matrices)
print("Resta de matrices:\n", resta_matrices)
print("Producto de matrices:\n", producto_matrices)
print("Inversa de la matriz 1:\n", inversa_matriz1)

Suma de matrices:
 [[ 6  8]
 [10 12]]
Resta de matrices:
 [[-4 -4]
 [-4 -4]]
Producto de matrices:
 [[19 22]
 [43 50]]
Inversa de la matriz 1:
 [[-2.   1. ]
 [ 1.5 -0.5]]


**4. Resolución de un Sistema de Ecuaciones Lineales**

* **Instrucción:** Resuelve el sistema de ecuaciones lineales dado por $Ax=b$, donde $A$ es una matriz $2 \times 2$ y b es un vector de 2 elementos.
* **Código:**

In [4]:
import numpy as np

A = np.array([[2, 3], [1, 2]])
b = np.array([8, 5])

x = np.linalg.solve(A, b)
print("Solución del sistema de ecuaciones:", x)

Solución del sistema de ecuaciones: [1. 2.]


**5. Simulación de Datos**

* **Instrucción:** Genera un array de 1000 números aleatorios que sigan una distribución normal con media 0 y desviación estándar 1. Calcula la media y desviación estándar del array generado.
* **Código:**

In [5]:
import numpy as np

datos_simulados = np.random.normal(0, 1, 1000)
media_simulada = np.mean(datos_simulados)
desviacion_simulada = np.std(datos_simulados)

print("Media de los datos simulados:", media_simulada)
print("Desviación estándar de los datos simulados:", desviacion_simulada)

Media de los datos simulados: 0.011644501415449184
Desviación estándar de los datos simulados: 0.9912405050662786


Con estos ejercicios, has consolidado tus conocimientos en NumPy y estás listo para explorar cómo esta poderosa herramienta se conecta con otras librerías esenciales en el análisis de datos. A medida que avances hacia los módulos de **Pandas** y **Matplotlib**, verás cómo NumPy se integra perfectamente para manipular y visualizar datos de manera eficiente.

Recuerda, NumPy es la base sobre la que construirás habilidades más avanzadas en análisis de datos.